version: '3.1'
networks:
  websocket-network:
    driver: bridge
services:
  rasa1:
    build: .
    volumes:
      - .:/app
    command: bash app.sh
    ports:
      - 5005:5005
  rasa_actions1:
    build: .
    volumes:
      - .:/app
    command: bash actions.sh
    ports:
      - 5055:5055 
