name: rasa-env
channels:
- default
- conda-forge
dependencies:
- ca-certificates=2017.08.26
- certifi=2017.11.5
- libedit=3.1
- libffi=3.2.1
- libgcc-ng=7.2.0
- libstdcxx-ng=7.2.0
- ncurses=6.0
- openssl=1.0.2n
- pip=9.0.1
- python=3.5.4
- readline=7.0
- setuptools=38.4.0
- sqlite=3.20.1
- tk=8.6.7
- wheel=0.30.0
- xz=5.2.3
- zlib=1.2.11
- pip:
  - apscheduler==3.5.0
  - fakeredis==0.9.0
  - future==0.16.0
  - greenlet==0.4.15
  - gevent==1.3.6
  - graphviz==0.8.3
  - pygraphviz==1.5
  - h5py==2.7.0
  - jsonpickle==0.9.4
  - keras==2.0.8
  - numpy==1.14.0
  - pandoc==1.0.0b2
  - redis==2.10.5
  - six==1.11.0
  - tensorflow==1.4.1
  - typing==3.6.2
  - networkx==1.11
  - fbmessenger==5.0.0
  - tqdm==4.19.5
  - ConfigArgParse==0.12.0
  - pykwalify==1.6.0
  - coloredlogs==7.3
  - ruamel.yaml==0.15.34
  - flask==0.12
  - scikit-learn==0.19.1
  - slackclient==1.1.0
  - requests==2.18.4
  - rasa_nlu==0.12.3
  - rasa_core==0.9.0a3
  - spacy==2.0.11
  - mattermostwrapper==2.1
  - twilio==6.11.0
  - colorhash==1.0.2